package CenterServerIdl.CenterServerPackage;


/**
* CenterServerIdl/CenterServerPackage/FieldNotFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerIdl.idl
* Tuesday, July 11, 2017 2:22:36 PM EDT
*/

public final class FieldNotFoundException extends org.omg.CORBA.UserException
{

  public FieldNotFoundException ()
  {
    super(FieldNotFoundExceptionHelper.id());
  } // ctor


  public FieldNotFoundException (String $reason)
  {
    super(FieldNotFoundExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class FieldNotFoundException
