package CenterServerIdl.CenterServerPackage;

/**
* CenterServerIdl/CenterServerPackage/InvalidValueExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerIdl.idl
* Tuesday, July 11, 2017 2:22:36 PM EDT
*/

public final class InvalidValueExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public CenterServerIdl.CenterServerPackage.InvalidValueException value = null;

  public InvalidValueExceptionHolder ()
  {
  }

  public InvalidValueExceptionHolder (CenterServerIdl.CenterServerPackage.InvalidValueException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CenterServerIdl.CenterServerPackage.InvalidValueExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CenterServerIdl.CenterServerPackage.InvalidValueExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CenterServerIdl.CenterServerPackage.InvalidValueExceptionHelper.type ();
  }

}
