package CenterServerIdl.CenterServerPackage;


/**
* CenterServerIdl/CenterServerPackage/InvalidValueException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerIdl.idl
* Tuesday, July 11, 2017 2:22:36 PM EDT
*/

public final class InvalidValueException extends org.omg.CORBA.UserException
{

  public InvalidValueException ()
  {
    super(InvalidValueExceptionHelper.id());
  } // ctor


  public InvalidValueException (String $reason)
  {
    super(InvalidValueExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidValueException
