package CenterServerIdl.CenterServerPackage;


/**
* CenterServerIdl/CenterServerPackage/InvalidLastNameException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerIdl.idl
* Tuesday, July 11, 2017 2:22:36 PM EDT
*/

public final class InvalidLastNameException extends org.omg.CORBA.UserException
{

  public InvalidLastNameException ()
  {
    super(InvalidLastNameExceptionHelper.id());
  } // ctor


  public InvalidLastNameException (String $reason)
  {
    super(InvalidLastNameExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidLastNameException
