package CenterServerIdl.CenterServerPackage;

/**
* CenterServerIdl/CenterServerPackage/InvalidLastNameExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerIdl.idl
* Tuesday, July 11, 2017 2:22:36 PM EDT
*/

public final class InvalidLastNameExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public CenterServerIdl.CenterServerPackage.InvalidLastNameException value = null;

  public InvalidLastNameExceptionHolder ()
  {
  }

  public InvalidLastNameExceptionHolder (CenterServerIdl.CenterServerPackage.InvalidLastNameException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CenterServerIdl.CenterServerPackage.InvalidLastNameExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CenterServerIdl.CenterServerPackage.InvalidLastNameExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CenterServerIdl.CenterServerPackage.InvalidLastNameExceptionHelper.type ();
  }

}
