package CenterServerIdl.CenterServerPackage;

/**
* CenterServerIdl/CenterServerPackage/RecordBeingTransferredHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerIdl.idl
* Tuesday, July 11, 2017 2:22:36 PM EDT
*/

public final class RecordBeingTransferredHolder implements org.omg.CORBA.portable.Streamable
{
  public CenterServerIdl.CenterServerPackage.RecordBeingTransferred value = null;

  public RecordBeingTransferredHolder ()
  {
  }

  public RecordBeingTransferredHolder (CenterServerIdl.CenterServerPackage.RecordBeingTransferred initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CenterServerIdl.CenterServerPackage.RecordBeingTransferredHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CenterServerIdl.CenterServerPackage.RecordBeingTransferredHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CenterServerIdl.CenterServerPackage.RecordBeingTransferredHelper.type ();
  }

}
