package CenterServerIdl.CenterServerPackage;


/**
* CenterServerIdl/CenterServerPackage/RecordNotFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerIdl.idl
* Tuesday, July 11, 2017 2:22:36 PM EDT
*/

public final class RecordNotFoundException extends org.omg.CORBA.UserException
{

  public RecordNotFoundException ()
  {
    super(RecordNotFoundExceptionHelper.id());
  } // ctor


  public RecordNotFoundException (String $reason)
  {
    super(RecordNotFoundExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class RecordNotFoundException
