package CenterServerIdl.CenterServerPackage;


/**
* CenterServerIdl/CenterServerPackage/RecordBeingTransferred.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerIdl.idl
* Tuesday, July 11, 2017 2:22:36 PM EDT
*/

public final class RecordBeingTransferred extends org.omg.CORBA.UserException
{

  public RecordBeingTransferred ()
  {
    super(RecordBeingTransferredHelper.id());
  } // ctor


  public RecordBeingTransferred (String $reason)
  {
    super(RecordBeingTransferredHelper.id() + "  " + $reason);
  } // ctor

} // class RecordBeingTransferred
