package CenterServerIdl.CenterServerPackage;

/**
* CenterServerIdl/CenterServerPackage/RecordNotFoundExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerIdl.idl
* Tuesday, July 11, 2017 2:22:36 PM EDT
*/

public final class RecordNotFoundExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public CenterServerIdl.CenterServerPackage.RecordNotFoundException value = null;

  public RecordNotFoundExceptionHolder ()
  {
  }

  public RecordNotFoundExceptionHolder (CenterServerIdl.CenterServerPackage.RecordNotFoundException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CenterServerIdl.CenterServerPackage.RecordNotFoundExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CenterServerIdl.CenterServerPackage.RecordNotFoundExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CenterServerIdl.CenterServerPackage.RecordNotFoundExceptionHelper.type ();
  }

}
