package com.classmanagement.exceptions;


import com.classmanagement.utils.corba.helper.RecordBeingTransferredExceptionHelper;

/**
* CenterServerIdl/CenterServerPackage/RecordBeingTransferredException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerIdl.idl
* Tuesday, July 11, 2017 1:08:27 PM EDT
*/

public final class RecordBeingTransferredException extends org.omg.CORBA.UserException
{

  public RecordBeingTransferredException ()
  {
    super(RecordBeingTransferredExceptionHelper.id());
  } // ctor


  public RecordBeingTransferredException (String $reason)
  {
    super(RecordBeingTransferredExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class RecordBeingTransferredException
