package com.classmanagement.utils.corba.holder;

import com.classmanagement.exceptions.FieldNotFoundException;
import com.classmanagement.utils.corba.helper.FieldNotFoundExceptionHelper;

/**
* CenterServerIdl/CenterServerPackage/FieldNotFoundExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerIdl.idl
* Sunday, June 18, 2017 12:56:33 PM EDT
*/

public final class FieldNotFoundExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public FieldNotFoundException value = null;

  public FieldNotFoundExceptionHolder ()
  {
  }

  public FieldNotFoundExceptionHolder (FieldNotFoundException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FieldNotFoundExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FieldNotFoundExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FieldNotFoundExceptionHelper.type ();
  }

}
