package com.classmanagement.utils.corba.holder;

import com.classmanagement.exceptions.InvalidValueException;
import com.classmanagement.utils.corba.helper.InvalidValueExceptionHelper;

/**
* CenterServerIdl/CenterServerPackage/InvalidValueExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerIdl.idl
* Sunday, June 18, 2017 12:56:33 PM EDT
*/

public final class InvalidValueExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public InvalidValueException value = null;

  public InvalidValueExceptionHolder ()
  {
  }

  public InvalidValueExceptionHolder (InvalidValueException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = InvalidValueExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    InvalidValueExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return InvalidValueExceptionHelper.type ();
  }

}
