package CenterServerIdl;


/**
* CenterServerIdl/CenterServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerIdl.idl
* Tuesday, July 11, 2017 2:22:36 PM EDT
*/

abstract public class CenterServerHelper
{
  private static String  _id = "IDL:CenterServerIdl/CenterServer:1.0";

  public static void insert (org.omg.CORBA.Any a, CenterServerIdl.CenterServer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CenterServerIdl.CenterServer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CenterServerIdl.CenterServerHelper.id (), "CenterServer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CenterServerIdl.CenterServer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CenterServerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CenterServerIdl.CenterServer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CenterServerIdl.CenterServer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CenterServerIdl.CenterServer)
      return (CenterServerIdl.CenterServer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CenterServerIdl._CenterServerStub stub = new CenterServerIdl._CenterServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CenterServerIdl.CenterServer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CenterServerIdl.CenterServer)
      return (CenterServerIdl.CenterServer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CenterServerIdl._CenterServerStub stub = new CenterServerIdl._CenterServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
