package CenterServerIdl;


/**
* CenterServerIdl/CenterServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerIdl.idl
* Tuesday, July 11, 2017 2:22:36 PM EDT
*/

public interface CenterServer extends CenterServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CenterServer
