package CenterServerIdl;


/**
* CenterServerIdl/CenterServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerIdl.idl
* Tuesday, July 11, 2017 2:22:36 PM EDT
*/

public interface CenterServerOperations 
{
  String createTRecord (String firstName, String lastName, String address, String phone, String specialization, String location, String managerId) throws CenterServerIdl.CenterServerPackage.InvalidLastNameException;
  String createSRecord (String firstName, String lastName, String coursesRegistered, String status, String statusDate, String managerId) throws CenterServerIdl.CenterServerPackage.InvalidLastNameException;
  String getRecordCounts (String managerId);
  void editRecord (String recordID, String fieldName, String newValue, String managerId) throws CenterServerIdl.CenterServerPackage.FieldNotFoundException, CenterServerIdl.CenterServerPackage.RecordNotFoundException, CenterServerIdl.CenterServerPackage.InvalidValueException;
  String show (String recordId) throws CenterServerIdl.CenterServerPackage.RecordNotFoundException;
  String transferRecord (String managerId, String recordId, String remoteCenterServerName) throws CenterServerIdl.CenterServerPackage.RecordNotFoundException, CenterServerIdl.CenterServerPackage.RecordBeingTransferred;
} // interface CenterServerOperations
