package com.classmanagement.exceptions;


import com.classmanagement.utils.corba.helper.FieldNotFoundExceptionHelper;

/**
* CenterServerIdl/CenterServerPackage/FieldNotFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerIdl.idl
* Sunday, June 18, 2017 12:56:33 PM EDT
*/

public final class FieldNotFoundException extends org.omg.CORBA.UserException
{

  public FieldNotFoundException ()
  {
    super(FieldNotFoundExceptionHelper.id());
  } // ctor


  public FieldNotFoundException (String $reason)
  {
    super(FieldNotFoundExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class FieldNotFoundException
