package com.classmanagement.exceptions;


import com.classmanagement.utils.corba.helper.RecordNotFoundExceptionHelper;

/**
* CenterServerIdl/CenterServerPackage/RecordNotFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerIdl.idl
* Sunday, June 18, 2017 12:56:33 PM EDT
*/

public final class RecordNotFoundException extends org.omg.CORBA.UserException
{

  public RecordNotFoundException ()
  {
    super(RecordNotFoundExceptionHelper.id());
  } // ctor


  public RecordNotFoundException (String $reason)
  {
    super(RecordNotFoundExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class RecordNotFoundException
