package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloApp.idl
* Tuesday, June 13, 2017 12:38:56 PM EDT
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
