package com.classmanagement.utils.corba.holder;

import com.classmanagement.interfaces.CenterServer;
import com.classmanagement.utils.corba.helper.CenterServerHelper;

/**
* CenterServerIdl/CenterServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl
* Sunday, June 18, 2017 12:56:33 PM EDT
*/

public final class CenterServerHolder implements org.omg.CORBA.portable.Streamable
{
  public CenterServer value = null;

  public CenterServerHolder ()
  {
  }

  public CenterServerHolder (CenterServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CenterServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CenterServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CenterServerHelper.type ();
  }

}
