package com.classmanagement.utils.corba.holder;

import com.classmanagement.exceptions.InvalidLastNameException;
import com.classmanagement.utils.corba.helper.InvalidLastNameExceptionHelper;

/**
* CenterServerIdl/CenterServerPackage/InvalidLastNameExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerIdl.idl
* Sunday, June 18, 2017 12:56:33 PM EDT
*/

public final class InvalidLastNameExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public InvalidLastNameException value = null;

  public InvalidLastNameExceptionHolder ()
  {
  }

  public InvalidLastNameExceptionHolder (InvalidLastNameException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = InvalidLastNameExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    InvalidLastNameExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return InvalidLastNameExceptionHelper.type ();
  }

}
